// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6G7O4JKiDyWf7tcxzoj7IAIDTNB25ZiU',
    appId: '1:153672671573:web:fd26f1fc9230bc01038fdc',
    messagingSenderId: '153672671573',
    projectId: 'unit-9asg-todolist',
    authDomain: 'unit-9asg-todolist.firebaseapp.com',
    storageBucket: 'unit-9asg-todolist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7J595JBsaU7U3QO-UQd8ngGqoKfmlcXk',
    appId: '1:153672671573:android:c93913792f7dbb87038fdc',
    messagingSenderId: '153672671573',
    projectId: 'unit-9asg-todolist',
    storageBucket: 'unit-9asg-todolist.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6G7O4JKiDyWf7tcxzoj7IAIDTNB25ZiU',
    appId: '1:153672671573:web:a7aa151199ed5512038fdc',
    messagingSenderId: '153672671573',
    projectId: 'unit-9asg-todolist',
    authDomain: 'unit-9asg-todolist.firebaseapp.com',
    storageBucket: 'unit-9asg-todolist.firebasestorage.app',
  );
}
